name: CI Pipeline

# Disparado em qualquer push no repositório
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixar o código do repositório
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurar o Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # Compilar o projeto com Maven
      - name: Build with Maven
        run: mvn clean compile

      # Executar testes
      - name: Run tests
        run: mvn test
